### PR TITLE
Fix: remove Bundler for Vagrant >= 1.9.0

### PR DESCRIPTION
**Pull request by theonedemon**
#310

### CODE REVIEW

**Comment by theonedemon** [comment]
Please accept merge request

**Comment by theonedemon** [comment]
@thommay I change my commit for your rules

**Comment by kylegoch** [comment]
I'm almost positive this is not the correct way to fix #310 .

As @thommay said, removing Bundler is a bigger discussion. And this file actually hasnt changed in about 2 years.

I suspect something actually changed in the vagrant code for 1.9.0 that broke vagrant-berkshelf integration. We need to look deeper into that issue than haphazardly removing code blocks.

**Comment by theonedemon** [comment]
@kylegoch read changelog vagrant https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md 
core: Remove Bundler integration for handling internal plugins [GH-7793, GH-8000, GH-8011, GH-8031]

"Bundler.with_clean_env" only clean environment variable on run command

**Pull request closed without merging**
