### PR TITLE
ensure that `berkshelf_enabled?` does not behave truthy if enabled is `MAYBE`

### LINKED ISSUE #261: vagrant-berkshelf should only be enabled if Berksfile is present
Just wondering, wasn't it the default behaviour that vagrant-berkshelf was only enabled when a `Berksfile` is present?

I'm noticing that vagrant-berkshelf *always* kicks in, sets up a shelf, and modifies the chef provisioner path, even if there is no Berksfile present at all!

This is vagrant-berkshelf 4.0.2 with vagrant 1.7.2

Is this the expected behaviour?

### PR DESCRIPTION
**Pull request by tknerr**
this should fix #261

### CODE REVIEW

**Comment by tknerr** [comment]
(tried adding a spec test, but my rspec foo seems to be too weak -- I failed mocking the `env` :-/)

**Comment by sethvargo** [comment]
I think I have a stub_env function somewhere, if not in here, it's in vagrant core. Ping me later if you can't find it

**Comment by reset** [comment]
@tknerr the test doesn't matter, this is an obvious change with almost no way of breaking

**Comment by tknerr** [comment]
@reset @sethvargo well, thanks for the merge. I feel a bit bad for not providing a test, but didn't have the energy to grok on that today... just not enough practice with rspec stubbing to write that down in a short time for a spare time rubyist like me... *sigh*

I'm confident though as my manual testing (once with and once without Berksfile) worked as expected...

Anyway... are you planning to cut another patch version release in the next few days? :grin:

**Comment by tknerr** [comment]
@reset mind releasing this bugfix as 4.0.3?

**Comment by reset** [comment]
@tknerr this is released as 4.0.3. Sorry for the delay, I read your tweet a few days back and forgot to do it when I got to work.

**Comment by tknerr** [comment]
@reset no worries at all, thanks a lot! :+1:

**Pull request merged**
